### ISSUE TITLE
BUG - Moving Windows When Grabbing From The Bottom Doesn't Work On External Monitor

### ISSUE THREAD

**Issue by Bryceshaw06** [pablopunk/SwiftShift#18] opened 2024-01-01 18:14 UTC
Hey, it's me again! When I was testing for the movement speed "issue" I was having trouble grabbing the window. It turns out that Swift Shift won't let me move a window if I pick up from the lower (roughly) 1/5 of it. This differs from Rectangle where you can pick up from anywhere on the window. If this is a feature, adding an option to toggle it on and off would be amazing. Thanks!

Video: https://share.cleanshot.com/pr3ghKCw

**Comment by pablopunk** [comment] 2024-01-02 10:54
Hmmm that's odd, I can't reproduce it. Can you share you screen size? Is it maybe related to having Rectangle Pro open at the same time?

https://github.com/pablopunk/SwiftShift/assets/4324982/b04a61bb-8a7c-4e53-a4f6-8cafcbe05999

**Comment by Bryceshaw06** [comment] 2024-01-02 19:07
You're right, it only happens on the external monitor. The monitor information is in this video: https://share.cleanshot.com/wGq9Jxst

**Comment by pablopunk** [comment] 2024-01-03 00:42
@Bryceshaw06 I started developing the app with an external monitor and I remember it did have some bugs, but I since moved to my laptop and didn't get any bug. This week I'll be back home and will try on my external monitor again

**Comment by pablopunk** [comment] 2024-01-05 09:20
@Bryceshaw06 can't manage to reproduce this, can you try the latest version? https://github.com/pablopunk/SwiftShift/releases

**Comment by pablopunk** [comment] 2024-01-07 13:14
Closing this one. Feel free to open it again if it's still happening

**Closed by pablopunk** 2024-01-07 13:14 UTC
Labels: bug, no reply

**Comment by Bryceshaw06** [comment] 2024-01-09 23:05
@pablopunk Sorry for the late reply, I was away from my computer for a while. The issue still persists on the latest version. I don't believe I'm able to reopen the issue if you (repo owner) closed it.

**Comment by pablopunk** [comment] 2024-01-12 15:14
I'm actually reproducing this now on my macbook, but a bit differently. When I set up my external monitor as my main screen and I get this behavior on my macbook screen, but the behavior is different: moving/resizing from the upper half(ish) activates the last window used on the external monitor. https://github.com/pablopunk/SwiftShift/issues/24

**Comment by pablopunk** [comment] 2024-01-16 19:35
Fixed in [v0.18.0](https://github.com/pablopunk/SwiftShift/releases/tag/0.18.0)

![CleanShot 2024-01-16 at 20 33 56@2x](https://github.com/pablopunk/SwiftShift/assets/4324982/92eddc2c-6759-4bfc-9595-b1daaba2b049)

Please test it and let me know @Bryceshaw06

**Comment by Bryceshaw06** [comment] 2024-01-16 21:49
Fixed!
