### ISSUE TITLE
SwiftShift does not seems to works on the secondary screen

### ISSUE THREAD

**Issue by FabienBehra38** [pablopunk/SwiftShift#33] opened 2024-02-24 19:07 UTC
I have one external monitor plugged into my mac and it's set up to be the main display. 

SwiftShift works perfectly fine on the main monitor (the external one) but does not work if i drag the window on the macbook screen. But if I unplug the monitor, then the MacBook screen becomes the main display and it's working perfectly. 
So think it's related to whom is the main display.

Material used:
- Macbook Air with Apple M1
- 16GB of RAM
- macos Sonoma 14.3.1
- External monitor : AOC Q27G2G4 27" (2560 x 1440)

**Comment by pablopunk** [comment] 2024-02-26 18:23
that's odd, I use an external monitor myself and have no issues with it. It did have it in the first versions of swift shift, but not anymore (since 0.18.0).

What version are you on? is it for all apps/windows?

**Comment by pablopunk** [comment] 2024-03-11 11:26
I will close this issue due to a lack of comments and inability to reproduce it. Feel free to open another issue with more info if you still reproduce this

**Closed by pablopunk** 2024-03-11 11:26 UTC
Labels: bug, can't reproduce
